version: 2

updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "Jani-shiv"
    assignees:
      - "Jani-shiv"
    commit-message:
      prefix: "📦"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "python"
    milestone: "Dependency Updates"
    
    # Security updates
    allow:
      - dependency-type: "all"
    
    # Ignore major version updates for stable packages
    ignore:
      - dependency-name: "Flask"
        update-types: ["version-update:semver-major"]
      - dependency-name: "SQLAlchemy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "reportlab"
        update-types: ["version-update:semver-major"]
    
    # Group related updates together
    groups:
      flask-ecosystem:
        patterns:
          - "Flask*"
          - "Werkzeug"
          - "Jinja2"
          - "itsdangerous"
          - "click"
      
      security-packages:
        patterns:
          - "cryptography"
          - "bcrypt"
          - "pyopenssl"
      
      testing-packages:
        patterns:
          - "pytest*"
          - "coverage"
          - "mock"
      
      ai-ml-packages:
        patterns:
          - "openai"
          - "transformers"
          - "torch"
          - "numpy"
          - "scipy"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "Jani-shiv"
    assignees:
      - "Jani-shiv"
    commit-message:
      prefix: "🔄"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
    
    # Group GitHub Actions updates
    groups:
      actions-core:
        patterns:
          - "actions/*"
      
      security-actions:
        patterns:
          - "github/codeql-action*"
          - "aquasecurity/*"
          - "securecodewarrior/*"

  # Docker (if we add Dockerfile later)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "Jani-shiv"
    assignees:
      - "Jani-shiv"
    commit-message:
      prefix: "🐳"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
      - "docker"